name: docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v1
      with:
        node-version: 15

    - name: Set git identity
      run: |
        git config --global user.name "Martin Adámek"
        git config --global user.email "banan23@gmail.com"

    - uses: actions/cache@v2
    - name: Cache node_modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Build docs
      run: |
        cd docs
        yarn
        yarn deploy
      env:
        GIT_USER: "B4nan:${{ secrets.GH_TOKEN }}"
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
