name: nightly

on:
  push:
    branches:
      - master # for testing
  schedule:
    - cron:  '0 6 * * *'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 15
      uses: actions/setup-node@v2-beta
      with:
        node-version: 15
        registry-url: https://registry.npmjs.org/

    - name: Install libkrb5-dev (for mongo)
      run: sudo apt install libkrb5-dev

    - name: Install
      run: |
        yarn
        echo "access=public" >> .npmrc
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Release nightly
      run: yarn release:next --yes --loglevel silly --no-verify-access
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
