name: nightly

on:
  push:
    branches:
      - master # for initial testing only
#on:
#  schedule:
#    - cron:  '0 6 * * *'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v2-beta
      with:
        node-version: 15
        registry-url: https://registry.npmjs.org/

    - name: Install libkrb5-dev (for mongo)
      run: sudo apt install libkrb5-dev

    - name: Release nightly
    - run: yarn
    - run: yarn release:next --yes --loglevel silly
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
